"""empty message

Revision ID: 680091456e23
Revises: 9db8ddfcccf7
Create Date: 2022-11-16 23:23:08.662050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680091456e23'
down_revision = '9db8ddfcccf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todolists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todolists', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
